sudo: required
language : 
  - go  
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc" 

os: 
  - linux
  - osx
  - windows

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(\.\d+)?(-\S*)?$/

install:
  - go get github.com/constabulary/gb/...
  - go get -u github.com/tools/godep/...
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling.git mashling
  - git clone https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd
  - cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling
  - cd mashling
  - godep restore
  - go install ./...
  - mashling help
  
script:
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - pushd mashling-cicd/sample-recipes
  - rm -rf builds
  - mkdir -p master-builds/latest builds/latest
  - chmod ugo+x ./build-recipes.sh  ./build-registry-recipes.sh
  - ./build-registry-recipes.sh
  - popd

after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"

deploy:
  provider: s3
  access_key_id: $SITE_KEY
  secret_access_key: $SITE_KEY_SECRET
  bucket: $AWS_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  on:
    all_branches: true
  local_dir: $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/sample-recipes/master-builds
  upload-dir: master-builds

notifications: 
  email: 
    on_failure: always
    on_success: always
    recipients:
      - rpolishe@tibco.com
      - lmekala@tibco.com
      - nthota@tibco.com
      - ykalidin@tibco.com
      - jpark@tibco.com
